<a href="https://colab.research.google.com/github/rajeevkumar05032004-jpg/.ipynb/blob/main/Numpy_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**ASSESSMENT-1**


#**Summer BootCamp**

#**NumPy**

#**Question No 1.**
A weather station recorded the temperature (°C) of a city for 10 days:
 [30, 32, 31, 29, 35, 36, 34, 33, 31, 30]
Perform the following tasks:
*   a) Create a 1D NumPy array using the given data.
*    b) Display the temperature on the 5th day using indexing.
*   c) Display the last day temperature using negative indexing
*    d) Use slicing to display temperatures from day 3 to day 7.
*    e)Display temperatures greater than 33°C.







 .




In [ ]:
import numpy as np

In [ ]:
#a. Create a 1D NumPy array using the given data.
temperature = np.array([30,32,31,29,35,36,34,33,31,30])
print("Temperature Array:")
print(temperature)

Temperature Array:
[30 32 31 29 35 36 34 33 31 30]


In [ ]:
#b. Display the temperature on the 5th day using indexing.
print("\ntemperature on 5th Day:")
print(temperature[4])


temperature on 5th Day:
35


In [ ]:
#c. Display the last day temperature using negative indexing
print("\nLast day Temprature:")
print(temperature[-1])


Last day Temprature:
30


In [ ]:
#d. Use slicing to display temperatures from day 3 to day 7.
print("\nTemperatures from Day 3 to Day 7:")
print(temperature[2:7])


Temperatures from Day 3 to Day 7:
[31 29 35 36 34]


In [ ]:
#e. Display temperatures greater than 33°C.
print("\nTemperatures Greater than 33°C:")
print(temperature[temperature>33])


Temperatures Greater than 33°C:
[35 36 34]


#**Question 2.**
Marks of 5 students in 4 subjects are given below:
Student  math  Science  English  Computer
S1       78    85       82       90
S2       88    79       91       86
S3       67    73       70       75
S4       92    88       84       89
S5       81    77       79       83
Perform the following tasks:

* Create a 2D NumPy array using the given data.
* Display marks of the 3rd student using indexing.
* Display marks of the first two subjects for all students using slicing.
* Display marks of the last student using negative indexing.
* Display marks of S2 and S3



.





In [ ]:
# a. Create a 2D NumPy array using the given data.
marks = np.array([[78,85,82,90],
                  [88,79,91,86],
                  [67,73,70,75],
                  [92,88,84,89],
                  [81,77,79,83]])
print("Student marks:")
print(marks)

Student marks:
[[78 85 82 90]
 [88 79 91 86]
 [67 73 70 75]
 [92 88 84 89]
 [81 77 79 83]]


In [ ]:
# b.Display marks of the 3rd student using indexing.
print("\nMarks of 3rd Student:")
print(marks[2])


Marks of 3rd Student:
[67 73 70 75]


In [ ]:
# c) Display marks of the first two subjects for all students
print("\nFirst Two Subjects of All Student:")
print(marks[:,0:2])


First Two Subjects of All Student:
[[78 85]
 [88 79]
 [67 73]
 [92 88]
 [81 77]]


In [ ]:
# d) Display marks of the last student using negative indexing
print("\nMarks of Last Student:")
print(marks[-1])


Marks of Last Student:
[81 77 79 83]


In [ ]:
# e) Display marks of S2 and S3
print("\nMarks of S2 and S3:")
print(marks[1:3])


Marks of S2 and S3:
[[88 79 91 86]
 [67 73 70 75]]


#**Question 3**
 A company recorded sales of 3 products for 4 months in 2 regions.

Product 1
Jan: [120,150]
Feb: [130,140]
Mar: [135,160]
Apr: [150,170]

Product 2
Jan: [200,210]
Feb: [195,205]
Mar: [220,230]
Apr: [210,225]

Product 3
Jan: [95,100]
Feb: [110,120]
Mar: [105,115]
Apr: [130,140]
Perform the following tasks:

a) Create a 3D NumPy array representing the sales data

b) Display the sales data of the 2nd product using indexing.

c) Display Region 1 sales for all products using slicing.

d) Display March sales for all products.


In [ ]:
#a) Create a 3D NumPy array representing the sales data
Sales = np.array([
#P1
[
    [120,150],
[130,140],
[135,160],
[150,170]],
 [
    #P2
[200,210],
[195,205],
[220,230],
[210,225]
    ],
   [ #P3
[95,100],
[110,120],
[105,115],
[130,140]
     ]
                   ])
print("Sales Data:")
print(Sales)

Sales Data:
[[[120 150]
  [130 140]
  [135 160]
  [150 170]]

 [[200 210]
  [195 205]
  [220 230]
  [210 225]]

 [[ 95 100]
  [110 120]
  [105 115]
  [130 140]]]


In [ ]:
# b) Display sales data of the 2nd product
print("\nSales Data of Product 2:")
print(Sales[1])


Sales Data of Product 2:
[[200 210]
 [195 205]
 [220 230]
 [210 225]]


In [ ]:
# c) Display Region 1 sales for all products
print("\nRegion 1 Sales for All Product:")
print(Sales[:, :, 0])


Region 1 Sales for All Product:
[[120 130 135 150]
 [200 195 220 210]
 [ 95 110 105 130]]


In [ ]:
# d) Display March sales for all products
print("\nMarch Sales for All Products:")
print(Sales[:, 2, :])


March Sales for All Products:
[[135 160]
 [220 230]
 [105 115]]
